spring.application.name=cachepractise

server.port=8089

spring.datasource.url=jdbc:mysql://localhost:3306/spring_boot
spring.datasource.username=root
spring.datasource.password=612900
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Maximum size of a single file
spring.servlet.multipart.max-file-size=10MB

# Maximum size of entire request (all files + form data)
spring.servlet.multipart.max-request-size=10MB